### ISSUE TITLE
Need some help configuring 

### ISSUE THREAD

**Issue by Tesla-P100FX** [SupImDos/homebridge-camera-swann#3]
**Describe The Bug:**
I followed  json guidelines and don't get an error but nothing shows up in home 

**To Reproduce:**

**Expected behavior:**
I was hopeing the camers would jsut show up in my Homekit app 

**Logs:**

```
Show the Homebridge logs here.
The log only shows the following:

Swann DVR is running on port 39059.
```

**Homebridge Config:**

This is how i built my Json i suspect i have the rtsp command wrong as i don't really understand it, does it need the [] and i dont understand the substream vs main or the CH) part of the command 

[
    {
        "name": "Swann DVR",
        "manufacturer": "swannview",
        "model": "HDR8-8200",
        "serialNumber": "0820130504AAWR093701234WCVU",
        "firmwareRevision": "V2.2.2 Build 130424",
        "videoConfig": {
            "mainStream": "-rtsp_transport tcp-i rtsp://[admin]:[12345]@[10.0.0.117]:[85]/ch0[8]/0",
            "subStream": "-rtsp_transport tcp -i rtsp://[admin]:[12345]@[10.0.0.117]:[85]/ch0[2]/1",
            "maxStreams": 8,
            "bitrateThreshold": 299,
            "videoPacketSize": 1378,
            "audioPacketSize": 188,
            "mapvideo": "0:v",
            "mapaudio": "0:a",
            "audio": true,
            "debug": false
        }
    }
]

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by SupImDos** [comment]
I haven't had a look at this plugin in a while, so not 100% sure if I am remembering everything correctly.

**Adding Cameras**
You need to add each camera separately in the config. Note that you don't need the square brackets, they are just placeholders. You also then need to pair each camera separately to HomeKit once everything is up and running in Homebridge - this is a separating pairing from when you originally paired the HomeBridge hub to your Homekit.

**RTSP***
Does your NVR/DVR support RTSP? You must have RTSP stream URLs for each camera to use this plugin.

**Channels**
Each camera on the NVR/DVR is on a separate channel. You will have to check this on your NVR/DVR software, or the port that the cameras are plugged into.

**Example Config**
For example, if your "Backyard" camera is on Channel 8 and your "Front Door" Camera is on Channel 2, assuming you have the correct RTSP address:

```
{
    "platform": "Camera-Swann",
    "cameras": [
        {
            "name": "Backyard Camera",
            "manufacturer": "swannview",
            "model": "HDR8-8200",
            "serialNumber": "0820130504AAWR093701234WCVU",
            "firmwareRevision": "V2.2.2 Build 130424",
            "videoConfig": {
                "mainStream": "-rtsp_transport tcp -i rtsp://admin:12345@10.0.0.117:85/ch08/0",
                "subStream": "-rtsp_transport tcp -i rtsp://admin:12345@10.0.0.117:85/ch08/1",
                "maxStreams": 2,
                "bitrateThreshold": 299,
                "videoPacketSize": 1378,
                "audioPacketSize": 188,
                "mapvideo": "0:v",
                "mapaudio": "0:a",
                "audio": true,
                "debug": false
            }
        },
        {
            "name": "Front Door Camera",
            "manufacturer": "swannview",
            "model": "HDR8-8200",
            "serialNumber": "0820130504AAWR093701234WCVU",
            "firmwareRevision": "V2.2.2 Build 130424",
            "videoConfig": {
                "mainStream": "-rtsp_transport tcp -i rtsp://admin:12345@10.0.0.117:85/ch02/0",
                "subStream": "-rtsp_transport tcp -i rtsp://admin:12345@10.0.0.117:85/ch02/1",
                "maxStreams": 2,
                "bitrateThreshold": 299,
                "videoPacketSize": 1378,
                "audioPacketSize": 188,
                "mapvideo": "0:v",
                "mapaudio": "0:a",
                "audio": true,
                "debug": false
            }
        }
    ]
}
```

**Main Stream and Sub Stream**
As per the README.md; The "mainStream" and "subStream" configuration options are just the RTSP URLs for the mainstream (high quality) and substream (low quality) on the NVR/DVR.

This bitrate threshold allows the plugin to select the mainStream or subStream based on the video bitrate requested by HomeKit. This means that when you are away from home, viewing the stream on Mobile 3G/4G will not consume as much data, and will probably work more smoothly.

Thanks!

**Comment by Tesla-P100FX** [comment]
I got further thank you but still no image in homekit

Log shows this

[Camera-Swann] Homekit requested: 299Kbps. Starting main stream from: Swann DVR
10/29/2020, 8:20:32 AM [Camera-Swann] ERROR: FFmpeg exited with code 1
10/29/2020, 8:20:37 AM [Camera-Swann] Snapshot from: Swann DVR @ 1280:720
10/29/2020, 8:24:54 AM [Camera-Swann] Snapshot from: Swann DVR @ 1280:720
10/29/2020, 8:24:56 AM [Camera-Swann] Homekit requested: 299Kbps. Starting main stream from: Swann DVR
10/29/2020, 8:24:56 AM [Camera-Swann] ERROR: FFmpeg exited with code 1
10/29/2020, 8:25:12 AM [Camera-Swann] Snapshot from: Swann DVR @ 1280:720
10/29/2020, 8:25:22 AM [Camera-Swann] Snapshot from: Swann DVR @ 1280:720
10/29/2020, 8:25:42 AM [Camera-Swann] Snapshot from: Swann DVR @ 1280:720
10/29/2020, 8:50:52 AM [Camera-Swann] Snapshot from: Swann DVR @ 1280:720
10/29/2020, 8:50:53 AM [Camera-Swann] Homekit requested: 299Kbps. Starting main stream from: Swann DVR
10/29/2020, 8:50:53 AM [Camera-Swann] ERROR: FFmpeg exited with code 1
10/29/2020, 8:51:01 AM [Camera-Swann] Snapshot from: Swann DVR @ 1280:720
10/29/2020, 8:51:04 AM [Camera-Swann] Homekit requested: 299Kbps. Starting main stream from: Swann DVR
10/29/2020, 8:51:05 AM [Camera-Swann] ERROR: FFmpeg exited with code 1

The config now is the following 

{
            "platform": "Camera-Swann",
            "plugin_map": {
                "plugin_name": "homebridge-camera-swann"
            },
            "cameras": [
                {
                    "name": "Swann DVR",
                    "manufacturer": "swannview",
                    "model": "HDR8-8200",
                    "serialNumber": "0820130504AAWR093701234WCVU",
                    "firmwareRevision": "V2.2.2 Build 130424",
                    "videoConfig": {
                        "mainStream": "-rtsp_transport tcp-i rtsp://admin:12345@10.0.0.117:554/ch1/0",
                        "subStream": "-rtsp_transport tcp -i rtsp://admin:12345@10.0.0.117:554/ch1/0/1",
                        "maxStreams": 1,
                        "bitrateThreshold": 299,
                        "videoPacketSize": 1378,
                        "audioPacketSize": 188,
                        "mapvideo": "0:v",
                        "mapaudio": "0:a",
                        "audio": true,
                        "debug": false
                    }
                }
            ]
        }

**Comment by SupImDos** [comment]
You must have FFMPEG installed and compiled to support libfdk-aac.

Also,

```
 "subStream": "-rtsp_transport tcp -i rtsp://admin:12345@10.0.0.117:554/ch1/0/1",
```

Should probably be (remove the extra /0):

```
 "subStream": "-rtsp_transport tcp -i rtsp://admin:12345@10.0.0.117:554/ch1/1",
```

Thanks

**Comment by Tesla-P100FX** [comment]
Still no joy.  Will you take one last look at my config and see if you have any other guidance 

{
            "platform": "Camera-Swann",
            "plugin_map": {
                "plugin_name": "homebridge-camera-swann"
            },
            "cameras": [
                {
                    "name": "Swann DVR",
                    "manufacturer": "swannview",
                    "model": "HDR8-8200",
                    "serialNumber": "0820130504AAWR093701234WCVU",
                    "firmwareRevision": "V2.2.2 Build 130424",
                    "videoConfig": {
                        "mainStream": "-rtsp_transport tcp-i rtsp://admin:12345@10.0.0.117:554/ch1/0",
                        "subStream": "-rtsp_transport tcp -i rtsp://admin:12345@10.0.0.117:554/ch1/1",
                        "maxStreams": 1,
                        "bitrateThreshold": 299,
                        "videoPacketSize": 1378,
                        "audioPacketSize": 188,
                        "mapvideo": "0:v",
                        "mapaudio": "0:a",
                        "audio": true,
                        "debug": false
                    }
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera FFmpeg",
            "videoProcessor": "libfdk-aac",
            "cameras": [
                {
                    "name": "Camera",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:12345@10.0.0.117:554/ch1/0",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "packetSize": 1316,
                        "debug": false
                    }
                }
            ]
        }
    ]
}

**Comment by Kangarw** [comment]
I'm having similar issues with my Swann camera setup.

Am I correct in using the IP to connect tot he NVR, not the individual cameras?  Using any of the IPs for the system appear to get a valid connection in the HomeBridge boot-up log, but if trying to select the camera from a Homekit app, the logs state this:

[tcp @ 0x4168540] Successfully connected to xxx.xxx.xxx.xxx port 9000
rtsp://user:password@xxx.xxx.xxx.xxx:9000/ch05/1: Invalid data found when processing input
[11/15/2020, 22:14:15] [Camera-Swann] ERROR: FFmpeg exited with code 1


I've tried using Homebridge plugin Homebridge Camera Ffmpeg getting similar results.

**Comment by SupImDos** [comment]
Unfortunately I won't be much help with either of these issues. You will be better off trying the [homebridge-camera-ffmpeg](https://github.com/Sunoo/homebridge-camera-ffmpeg#readme) plugin and opening an issue there if you have problems. It has had huge improvements since I created this plugin and is likely simpler to configure, so I would recommend for people to use that from now on.
