### ISSUE TITLE
Set up 

### ISSUE THREAD

**Issue by TomWilson888** [SupImDos/homebridge-camera-swann#5]
**Describe Your Problem:**
Hi, I hope you can help. Currently use XMEYE to view camera, honestly cannot remember how I set this up. But from the app settings it appears only a serial number and user&pass. How would I add this on the config file?

**Logs:**

```
Show the Homebridge logs here.
Remove any sensative information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here. 
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by SupImDos** [comment]
Unfortunately, you can't configure this plugin with only the Serial Number.

You need to know the IP address of your DVR/NVR on your network, and be able to setup an RTSP stream from them, which this plugin utilizes.
