### ISSUE TITLE
re Swann not showing up in HomeKit   Oliver 

### ISSUE THREAD

**Issue by oliverchapple** [SupImDos/homebridge-camera-swann#6]
hi

I'm trying to add the cameras rtsp stream which I done I have test with vlc so I know it works.

what does Interface Name mean.  also its not showing up in the log or HomeKit 

many thanks Oliver

**Comment by SupImDos** [comment]
Would you be able to post your config?

**Comment by oliverchapple** [comment]
![Screenshot 2021-03-13 at 13 07 04](https://user-images.githubusercontent.com/42448591/111031000-41de8a00-83fd-11eb-9b89-52949c546deb.png)

here's my config

from Oliver

**Comment by SupImDos** [comment]
What Swann NVR do you have?

As this plugin uses `vcodec: copy` your streams must be configured to output an appropriate `h.264` stream as per the image on the front page of this plugin:

<img src="https://user-images.githubusercontent.com/62866982/80780499-bcb20400-8ba1-11ea-8097-ab7dfb5d2873.png">

If you have already setup an appropriate `h.264` stream, and the snapshot is working, then you may have to decrease the quality (bitrate and resolution) of the stream.

**Comment by oliverchapple** [comment]
does it matter if its an dvr that useing rstp

**Comment by SupImDos** [comment]
This plugin in particular is for the Swann branded NVRs/DVRs. Is that what you own?

**Comment by oliverchapple** [comment]
yep dvr Swann

**Comment by SupImDos** [comment]
Which one? Have you set it up to output a `h.264` Stream? Screenshot the settings of the DVR like I did in my first comment.
