### ISSUE TITLE
help with homebridge setup

### ISSUE THREAD

**Issue by liam8888999** [SupImDos/homebridge-camera-swann#7]
**Describe Your Problem:**
Im not getting motion notifications.
I would expect this to give me push notifications when motion is detected

```
Show the Homebridge logs here.
Remove any sensative information.
```

**Homebridge Config:**

``
{
    "cameras": [
        {
            "name": "front yard",
            "manufacturer": "swann",
            "model": "nvr",
            "motion": true,
            "videoConfig": {
                "mainStream": "-i rtsp://admin:xxxx@192.168.0.210/ch01/1",
                "subStream": "-i rtsp://admin:xxxx@192.168.0.210/ch01/1",
                "audio": true
            }
        }
    ],
    "_bridge": {
        "username": "0E:46:53:DE:A5:84",
        "port": 41883
    },
    "platform": "Camera-Swann"
}
```

**Comment by SupImDos** [comment]
@liam8888999 This plugin doesn't support motion sensing. I think you will have more success with the plugin this was forked from (which is also currently maintained): https://github.com/Sunoo/homebridge-camera-ffmpeg
